// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNb9ods43KA2kStxV-pbjNP3lYg3K5xj0',
    appId: '1:28733812980:web:26392eacd559d8a9d0aea1',
    messagingSenderId: '28733812980',
    projectId: 'chess-4c70d',
    authDomain: 'chess-4c70d.firebaseapp.com',
    storageBucket: 'chess-4c70d.firebasestorage.app',
    measurementId: 'G-T0ZW2XCN1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr1YlvtOrdAMJ7z5fUgp6srwU5j05J_I8',
    appId: '1:28733812980:android:fbdae7ce8cc6f3f3d0aea1',
    messagingSenderId: '28733812980',
    projectId: 'chess-4c70d',
    storageBucket: 'chess-4c70d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDztZRe7YFHUaiMro2AtKqKh3I4PMyP-MU',
    appId: '1:28733812980:ios:c84d5c915e55c93bd0aea1',
    messagingSenderId: '28733812980',
    projectId: 'chess-4c70d',
    storageBucket: 'chess-4c70d.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDztZRe7YFHUaiMro2AtKqKh3I4PMyP-MU',
    appId: '1:28733812980:ios:c84d5c915e55c93bd0aea1',
    messagingSenderId: '28733812980',
    projectId: 'chess-4c70d',
    storageBucket: 'chess-4c70d.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNb9ods43KA2kStxV-pbjNP3lYg3K5xj0',
    appId: '1:28733812980:web:ed4b9c8acbf58820d0aea1',
    messagingSenderId: '28733812980',
    projectId: 'chess-4c70d',
    authDomain: 'chess-4c70d.firebaseapp.com',
    storageBucket: 'chess-4c70d.firebasestorage.app',
    measurementId: 'G-SBX2SZ1HKL',
  );
}
